version: '3.8'

services:
  turtlebot:
    build:
      context: .
      dockerfile: Dockerfile
    image: osrf/roslhumbledesktop
    container_name: ros2_humble
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/ausros_turtlebot
    command: /bin/bash
    tty: true

